### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Ilmereth** [fabriziosalmi/proxmox-lxc-autoscale#14]
**Describe the bug**
I am running ProyMox 8.3.0, Kernel Version Linux 6.8.12-4-pve (2024-11-06T15:04Z)

I am installing via 

curl -sSL https://raw.githubusercontent.com/fabriziosalmi/proxmox-lxc-autoscale/main/install.sh | bash

and Iget no Errors.
Using 

systemctl status lxc_autoscale.service

I get the following:

● lxc_autoscale.service - LXC AutoScale Daemon
     Loaded: loaded (/etc/systemd/system/lxc_autoscale.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-11-29 12:04:31 CET; 2s ago
       Docs: https://github.com/fabriziosalmi/proxmox-lxc-autoscale
   Main PID: 1514480 (python3)
      Tasks: 1 (limit: 76765)
     Memory: 30.3M
        CPU: 10.292s
     CGroup: /system.slice/lxc_autoscale.service
             └─1514480 /usr/bin/python3 /usr/local/bin/lxc_autoscale/lxc_autoscale.py

Nov 29 12:04:34 blackbox python3[1514480]: Traceback (most recent call last):
Nov 29 12:04:34 blackbox python3[1514480]:   File "/usr/local/bin/lxc_autoscale/resource_manager.py", line 129, in main_loop
Nov 29 12:04:34 blackbox python3[1514480]:     scaling_manager.adjust_resources(containers, energy_mode)
Nov 29 12:04:34 blackbox python3[1514480]:   File "/usr/local/bin/lxc_autoscale/scaling_manager.py", line 159, in adjust_resources
Nov 29 12:04:34 blackbox python3[1514480]:     total_memory = get_total_memory()
Nov 29 12:04:34 blackbox python3[1514480]:                    ^^^^^^^^^^^^^^^^^^
Nov 29 12:04:34 blackbox python3[1514480]:   File "/usr/local/bin/lxc_autoscale/lxc_utils.py", line 196, in get_total_memory
Nov 29 12:04:34 blackbox python3[1514480]:     total_memory = int(run_command("free -m | awk '/Mem:/ {print $2}'"))
Nov 29 12:04:34 blackbox python3[1514480]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 29 12:04:34 blackbox python3[1514480]: ValueError: invalid literal for int() with base 10: ''

When I use 

curl -sSL https://raw.githubusercontent.com/fabriziosalmi/proxmox-lxc-autoscale/main/lxc_autoscale/lxc_autoscale_autoconf.sh | bash

I get the following:
🚀 Starting LXC autoscale configuration...
📊 Total containers: 5 (Running: 5, Stopped: 0)
🛑 Stopped containers: 
✅ Running containers: 100 101 244 249 254
Preparing to ask about ignored containers...
💻 Detected running LXC containers: 100 101 244 249 254
⚠️ No containers were ignored.
Debug: Ignored containers: 
Debug: Running containers before filtering: 100 101 244 249 254
Debug: Processed containers after filtering: 100 101 244 249 254
🔍 Total resources on Proxmox host: 20 cores,  MB memory
🔍 Total resources used by selected containers: 26 cores, 24064 MB memory
🔍 Remaining resources: -6 cores, -24064 MB memory
⚙️  Configuring TIER sections...

I tried rebooting, systemctl daemon-reload after every step and systemctl restart lxc_autoscale.service but to no avail.

**To Reproduce**

Uninstall using 

curl -sSL https://raw.githubusercontent.com/fabriziosalmi/proxmox-lxc-autoscale/main/uninstall.sh | bash

and reinstalling.

**Comment by fabriziosalmi** [comment]
I tried a more solid method with the [latest commit](https://github.com/fabriziosalmi/proxmox-lxc-autoscale/commit/9e06b3c4bb395bded0b7e3deee1989630cb67ab1)

Please let me know if this is fixed now, thank you ☕
