### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Ilmereth** [fabriziosalmi/proxmox-lxc-autoscale#16]
After installing and configuring with your scripts, I still get this anoying error:

● lxc_autoscale.service - LXC AutoScale Daemon
     Loaded: loaded (/etc/systemd/system/lxc_autoscale.service; enabled; preset: enabled)
     Active: active (running) since Sat 2024-11-30 10:11:48 CET; 1 day 5h ago
       Docs: https://github.com/fabriziosalmi/proxmox-lxc-autoscale
   Main PID: 520562 (python3)
      Tasks: 1 (limit: 76765)
     Memory: 30.5M
        CPU: 29min 55.004s
     CGroup: /system.slice/lxc_autoscale.service
             └─520562 /usr/bin/python3 /usr/local/bin/lxc_autoscale/lxc_autoscale.py

Dez 01 15:18:56 blackbox python3[520562]: Traceback (most recent call last):
Dez 01 15:18:56 blackbox python3[520562]:   File "/usr/local/bin/lxc_autoscale/resource_manager.py", line 129, in main_loop
Dez 01 15:18:56 blackbox python3[520562]:     scaling_manager.adjust_resources(containers, energy_mode)
Dez 01 15:18:56 blackbox python3[520562]:   File "/usr/local/bin/lxc_autoscale/scaling_manager.py", line 159, in adjust_resources
Dez 01 15:18:56 blackbox python3[520562]:     total_memory = get_total_memory()
Dez 01 15:18:56 blackbox python3[520562]:                    ^^^^^^^^^^^^^^^^^^
Dez 01 15:18:56 blackbox python3[520562]:   File "/usr/local/bin/lxc_autoscale/lxc_utils.py", line 196, in get_total_memory
Dez 01 15:18:56 blackbox python3[520562]:     total_memory = int(run_command("free -m | awk '/Mem:/ {print $2}'"))
Dez 01 15:18:56 blackbox python3[520562]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dez 01 15:18:56 blackbox python3[520562]: ValueError: invalid literal for int() with base 10: ''

**Comment by fabriziosalmi** [comment]
Tried [this approach](https://github.com/fabriziosalmi/proxmox-lxc-autoscale/commit/5cabc90e8296a678b7fdee4970ca9613d9a2c367) since I lack some free time at the moment :)

**Comment by Ilmereth** [comment]
...and it works.
NICE!
Thanks a lot for your work and time fixing this.
Have a great Weekend/Week.
