### ISSUE TITLE
proxmox-vm-autoscale

### ISSUE THREAD

**Issue by yangsm88888** [fabriziosalmi/proxmox-lxc-autoscale#3]
Can the automatic expansion of CPU and memory functions be added to the virtual machine?

thank you

**Comment by fabriziosalmi** [comment]
> Can the automatic expansion of CPU and memory functions be added to the virtual machine?
> 
> thank you

Helo, vm management is still under testing. there are constraints and challenges.. I am not sure I will be able to release vm support very soon without some contributors coding assistance.

**Comment by yangsm88888** [comment]
Thank you, I'm waiting for your good news. You can first release a basic function, with the virtual machine memory and CPU as conditions.

**Comment by fabriziosalmi** [comment]
> Thank you, I'm waiting for your good news. You can first release a basic function, with the virtual machine memory and CPU as conditions.

Good news :) I just tested and released an initial, working version, including installer easy way (curl bash). Just released here: https://github.com/fabriziosalmi/proxmox-vm-autoscale), the point is that it can be run alongside this project with no issues then people can just use one or both, depending on their own setup 🎉

**Comment by yangsm88888** [comment]
Thank you very much for your work




月光
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fabriziosalmi/proxmox-lxc-autoscale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月28日(星期六) 晚上8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fabriziosalmi/proxmox-lxc-autoscale] proxmox-vm-autoscale (Issue #3)





  
Thank you, I'm waiting for your good news. You can first release a basic function, with the virtual machine memory and CPU as conditions.
  
Good news :) I just tested and released an initial, working version, including installer easy way (curl bash). Just released here: https://github.com/fabriziosalmi/proxmox-vm-autoscale), the point is that it can be run alongside this project with no issues then people can just use one or both, depending on their own setup 🎉
